### ISSUE TITLE
Java ppa no longer available breaking the Docker image

### ISSUE THREAD

**Issue by osmestad** [dhs-shine/docker-tizenstudio#2]
We have been using a variant of your Dockerfile for some time and it has been working great, thanks!

Now it unfortunately fails with:
```
Package 'oracle-java8-installer' has no installation candidate
The command '/bin/sh -c echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections   && add-apt-repository -y ppa:webupd8team/java   && apt-get update   && apt-get install -y oracle-java8-installer   && rm -rf /var/lib/apt/lists/*   && rm -rf /var/cache/oracle-jdk8-installer' returned a non-zero code: 100
```

I assume that is because the package is no longer available: https://launchpad.net/~webupd8team/+archive/ubuntu/java 
Before we start trying different packages I figured I'd ask if you knew what is the proper fix? Would for instance switching to Open JDK work with Tizen?

**Comment by dhs-shine** [comment]
Hi @osmestad.
After replace jdk from oraclejdk8 to openjdk8, there's no build issue for my usecase, but openjdk8 is not supported for tizen studio officially now. (oracle jdk8, 9 and openjdk10 are only supported)
https://developer.tizen.org/community/tip-tech/does-tizen-studio-support-jdkopenjdk-11
It would be better to use openjdk10 and tizen studio >= 3.1.

**Comment by osmestad** [comment]
Thank you, 
We went the same route and switched to openjdk8, it does seem to work for us too, at least it builds correctly (have not fully tested the artefact on a TV yet).
